theme: jekyll-theme-cayman

title: Blake Lochmandy
description: USC CS Games (M.S.) · Game Developer & Full Stack Engineer with a focus on creative tech, prototyping, and structure.
author: Blake Lochmandy

markdown: kramdown
permalink: pretty
